import authRoutes from "./auth.route.js";
import profileRoutes from "./profile.route.js";
import repRoutes from "./rep.route.js";
import supervisorRoutes from "./supervisor.route.js";
import managerRoutes from "./manager.route.js";
import doctorRoutes from "./doctor.route.js";
import hospitalRoutes from "./hospital.route.js";
import visitRoutes from "./visit.route.js";
import requestRoutes from "./request.route.js";
import planRoutes from "./plan.route.js";
import coachingReportRoutes from "./coaching-reports.route.js";
import regionRoutes from "./region.route.js";
import subRegionRoutes from "./subRegion.route.js";
import appraisalRoutes from "./appraisal.route.js";
import forecastRoutes from "./forecast.route.js";

export default (app) => {
  app.use("/api/auth", authRoutes);
  app.use("/api/profiles", profileRoutes);
  app.use("/api/reps", repRoutes);
  app.use("/api/supervisors", supervisorRoutes);
  app.use("/api/managers", managerRoutes);
  app.use("/api/doctors", doctorRoutes);
  app.use("/api/hospitals", hospitalRoutes);
  app.use("/api/visits", visitRoutes);
  app.use("/api/requests", requestRoutes);
  app.use("/api/plans", planRoutes);
  app.use("/api/coaching-reports", coachingReportRoutes);
  app.use("/api/regions", regionRoutes);
  app.use("/api/sub-regions", subRegionRoutes);
  app.use("/api/appraisals", appraisalRoutes);
  app.use("/api/forecasts", forecastRoutes);
};
