-- AlterTable
ALTER TABLE "Visit" ADD COLUMN     "planId" TEXT,
ALTER COLUMN "time" DROP NOT NULL;

-- AddForeignKey
ALTER TABLE "Visit" ADD CONSTRAINT "Visit_planId_fkey" FOREIGN KEY ("planId") REFERENCES "Plan"("id") ON DELETE SET NULL ON UPDATE CASCADE;
